PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?class ?classLabel
WHERE {
    ?class (rdfs:subClassOf)* <http://dbpedia.org/ontology/Agent> .
    ?class rdfs:label ?classLabel .
    FILTER ( LANG(?classLabel) = "en" )
}
LIMIT 10
